/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FormuserComponent {
        "nesimoMultiplo3": number;
        "nesimoPrimo": number;
    }
    interface ResultComponent {
        "resNesimoMultiplo3": number;
        "resNesimoPrimo": number;
    }
}
declare global {
    interface HTMLFormuserComponentElement extends Components.FormuserComponent, HTMLStencilElement {
    }
    var HTMLFormuserComponentElement: {
        prototype: HTMLFormuserComponentElement;
        new (): HTMLFormuserComponentElement;
    };
    interface HTMLResultComponentElement extends Components.ResultComponent, HTMLStencilElement {
    }
    var HTMLResultComponentElement: {
        prototype: HTMLResultComponentElement;
        new (): HTMLResultComponentElement;
    };
    interface HTMLElementTagNameMap {
        "formuser-component": HTMLFormuserComponentElement;
        "result-component": HTMLResultComponentElement;
    }
}
declare namespace LocalJSX {
    interface FormuserComponent {
        "nesimoMultiplo3"?: number;
        "nesimoPrimo"?: number;
    }
    interface ResultComponent {
        "resNesimoMultiplo3"?: number;
        "resNesimoPrimo"?: number;
    }
    interface IntrinsicElements {
        "formuser-component": FormuserComponent;
        "result-component": ResultComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "formuser-component": LocalJSX.FormuserComponent & JSXBase.HTMLAttributes<HTMLFormuserComponentElement>;
            "result-component": LocalJSX.ResultComponent & JSXBase.HTMLAttributes<HTMLResultComponentElement>;
        }
    }
}
